name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.0
  

  cupertino_icons: ^1.0.6
  syncfusion_flutter_calendar: ^24.1.47


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
