name: flutter_application_verify
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # Додайте цю строчку у ваш pubspec.yaml файл:
  http: ^1.2.1
  parse_server_sdk_flutter: 3.2.5
